// <auto-generated />
// Entity for table account, derived from CVACT01Y.
// Field prefix 'ACCT' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("account")]
public class Account
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("active_status")]
    public string ActiveStatus { get; set; } = string.Empty;

    [Column("curr_bal")]
    [Precision(12, 2)]
    public decimal CurrBal { get; set; }

    [Column("credit_limit")]
    [Precision(12, 2)]
    public decimal CreditLimit { get; set; }

    [Column("cash_credit_limit")]
    [Precision(12, 2)]
    public decimal CashCreditLimit { get; set; }

    [Column("open_date")]
    public string OpenDate { get; set; } = string.Empty;

    [Column("expiraion_date")]
    public string ExpiraionDate { get; set; } = string.Empty;

    [Column("reissue_date")]
    public string ReissueDate { get; set; } = string.Empty;

    [Column("curr_cyc_credit")]
    [Precision(12, 2)]
    public decimal CurrCycCredit { get; set; }

    [Column("curr_cyc_debit")]
    [Precision(12, 2)]
    public decimal CurrCycDebit { get; set; }

    [Column("addr_zip")]
    public string AddrZip { get; set; } = string.Empty;

    [Column("group_id")]
    public string GroupId { get; set; } = string.Empty;

}