// <auto-generated />
// Entity for table carddemo_commarea, derived from COCOM01Y.
// Field prefix 'CDEMO' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("carddemo_commarea")]
public class CarddemoCommarea
{
    [Column("from_tranid")]
    public string FromTranid { get; set; } = string.Empty;

    [Column("from_program")]
    public string FromProgram { get; set; } = string.Empty;

    [Column("to_tranid")]
    public string ToTranid { get; set; } = string.Empty;

    [Column("to_program")]
    public string ToProgram { get; set; } = string.Empty;

    [Column("user_id")]
    public string UserId { get; set; } = string.Empty;

    [Column("user_type")]
    public string UserType { get; set; } = string.Empty;

    [Column("pgm_context")]
    public int PgmContext { get; set; }

    [Column("cust_id")]
    public int CustId { get; set; }

    [Column("cust_fname")]
    public string CustFname { get; set; } = string.Empty;

    [Column("cust_mname")]
    public string CustMname { get; set; } = string.Empty;

    [Column("cust_lname")]
    public string CustLname { get; set; } = string.Empty;

    [Column("acct_id")]
    public long AcctId { get; set; }

    [Column("acct_status")]
    public string AcctStatus { get; set; } = string.Empty;

    [Column("card_num")]
    public long CardNum { get; set; }

    [Column("last_map")]
    public string LastMap { get; set; } = string.Empty;

    [Column("last_mapset")]
    public string LastMapset { get; set; } = string.Empty;

}