// <auto-generated />
// Entity for table card_xref, derived from CVACT03Y.
// Field prefix 'XREF' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("card_xref")]
public class CardXref
{
    [Column("card_num")]
    public string CardNum { get; set; } = string.Empty;

    [Column("cust_id")]
    public int CustId { get; set; }

    [Column("acct_id")]
    public long AcctId { get; set; }

}