// <auto-generated />
// Entity for table ccda_common_messages, derived from CSMSG01Y.
// Field prefix 'CCDA' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("ccda_common_messages")]
public class CcdaCommonMessages
{
    [Column("msg_thank_you")]
    public string MsgThankYou { get; set; } = string.Empty;

    [Column("msg_invalid_key")]
    public string MsgInvalidKey { get; set; } = string.Empty;

}