// <auto-generated />
// Entity for table ccda_screen_title, derived from COTTL01Y.
// Field prefix 'CCDA' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("ccda_screen_title")]
public class CcdaScreenTitle
{
    [Column("title01")]
    public string Title01 { get; set; } = string.Empty;

    [Column("title02")]
    public string Title02 { get; set; } = string.Empty;

    [Column("thank_you")]
    public string ThankYou { get; set; } = string.Empty;

}