// <auto-generated />
#nullable enable
using Microsoft.EntityFrameworkCore;

namespace CardDemo.OnlineTransactionManagement.Data;

public class OnlineTransactionManagementDbContext : DbContext
{
    public OnlineTransactionManagementDbContext(DbContextOptions<OnlineTransactionManagementDbContext> options) : base(options) { }

    public DbSet<CarddemoCommarea> CarddemoCommareas => Set<CarddemoCommarea>();
    public DbSet<CcdaScreenTitle> CcdaScreenTitles => Set<CcdaScreenTitle>();
    public DbSet<WsDateTime> WsDateTimes => Set<WsDateTime>();
    public DbSet<CcdaCommonMessages> CcdaCommonMessagess => Set<CcdaCommonMessages>();
    public DbSet<Account> Accounts => Set<Account>();
    public DbSet<CardXref> CardXrefs => Set<CardXref>();
    public DbSet<Tran> Trans => Set<Tran>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        b.HasDefaultSchema("onlinetransactionmanagement");
        base.OnModelCreating(b);
    }
}