// <auto-generated />
// Entity for table tran, derived from CVTRA05Y.
// Field prefix 'TRAN' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("tran")]
public class Tran
{
    [Key]
    [Column("id")]
    public string Id { get; set; } = string.Empty;

    [Column("type_cd")]
    public string TypeCd { get; set; } = string.Empty;

    [Column("cat_cd")]
    public int CatCd { get; set; }

    [Column("source")]
    public string Source { get; set; } = string.Empty;

    [Column("desc")]
    public string Desc { get; set; } = string.Empty;

    [Column("amt")]
    [Precision(11, 2)]
    public decimal Amt { get; set; }

    [Column("merchant_id")]
    public int MerchantId { get; set; }

    [Column("merchant_name")]
    public string MerchantName { get; set; } = string.Empty;

    [Column("merchant_city")]
    public string MerchantCity { get; set; } = string.Empty;

    [Column("merchant_zip")]
    public string MerchantZip { get; set; } = string.Empty;

    [Column("card_num")]
    public string CardNum { get; set; } = string.Empty;

    [Column("orig_ts")]
    public string OrigTs { get; set; } = string.Empty;

    [Column("proc_ts")]
    public string ProcTs { get; set; } = string.Empty;

}