// <auto-generated />
// Entity for table ws_date_time, derived from CSDAT01Y.
// Field prefix 'WS' stripped from column names.
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardDemo.OnlineTransactionManagement.Data;

[Table("ws_date_time")]
public class WsDateTime
{
    [Column("curdate_year")]
    public int CurdateYear { get; set; }

    [Column("curdate_month")]
    public int CurdateMonth { get; set; }

    [Column("curdate_day")]
    public int CurdateDay { get; set; }

    [Column("curtime_hours")]
    public int CurtimeHours { get; set; }

    [Column("curtime_minute")]
    public int CurtimeMinute { get; set; }

    [Column("curtime_second")]
    public int CurtimeSecond { get; set; }

    [Column("curtime_milsec")]
    public int CurtimeMilsec { get; set; }

    [Column("curdate_mm")]
    public int CurdateMm { get; set; }

    [Column("curdate_dd")]
    public int CurdateDd { get; set; }

    [Column("curdate_yy")]
    public int CurdateYy { get; set; }

    [Column("curtime_hh")]
    public int CurtimeHh { get; set; }

    [Column("curtime_mm")]
    public int CurtimeMm { get; set; }

    [Column("curtime_ss")]
    public int CurtimeSs { get; set; }

    [Column("timestamp_dt_yyyy")]
    public int TimestampDtYyyy { get; set; }

    [Column("timestamp_dt_mm")]
    public int TimestampDtMm { get; set; }

    [Column("timestamp_dt_dd")]
    public int TimestampDtDd { get; set; }

    [Column("timestamp_tm_hh")]
    public int TimestampTmHh { get; set; }

    [Column("timestamp_tm_mm")]
    public int TimestampTmMm { get; set; }

    [Column("timestamp_tm_ss")]
    public int TimestampTmSs { get; set; }

    [Column("timestamp_tm_ms6")]
    public int TimestampTmMs6 { get; set; }

}