#nullable enable

namespace CardDemo.OnlineTransactionManagement.Domain;

/// <summary>A single financial transaction (payment, purchase, etc.) against a card</summary>
public class Transaction
{
    /// <summary>generated by incrementing the last transaction ID</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>e.g. '02' for bill payment; see open_questions for enum</summary>
    public string TypeCode { get; set; } = string.Empty;

    /// <summary>e.g. 2 for bill payment; see open_questions for enum</summary>
    public int CategoryCode { get; set; }

    /// <summary>Origination channel, e.g. 'POS TERM'</summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>Human-readable description, e.g. 'BILL PAYMENT - ONLINE'</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Monetary value — decimal, never double</summary>
    public decimal Amount { get; set; }

    /// <summary>FK to card_cross_references.card_number</summary>
    public string CardNumber { get; set; } = string.Empty;

    /// <summary>Proven timestamp field</summary>
    public DateTimeOffset OriginatedAt { get; set; }

    /// <summary>Proven timestamp field</summary>
    public DateTimeOffset ProcessedAt { get; set; }

    public MerchantInfo Merchant { get; set; } = new();
}