#nullable enable

namespace CardDemo.OnlineTransactionManagement.Domain;

/// <summary>A single financial transaction (payment, purchase, etc.) posted against a card</summary>
public class Transaction
{
    /// <summary>generated by incrementing the last transaction ID</summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>Two-character type code, e.g. '02' for bill payment</summary>
    public string TypeCode { get; set; } = string.Empty;

    /// <summary>Numeric category, e.g. 2 for bill payment</summary>
    public int CategoryCode { get; set; }

    /// <summary>Origination channel, e.g. 'POS TERM'</summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>Human-readable description, e.g. 'BILL PAYMENT - ONLINE'</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Transaction amount. Money — decimal, never double</summary>
    public decimal Amount { get; set; }

    /// <summary>Proven timestamp — when the transaction was initiated</summary>
    public DateTimeOffset OriginatedAt { get; set; }

    /// <summary>Proven timestamp — when the transaction was processed</summary>
    public DateTimeOffset ProcessedAt { get; set; }

    /// <summary>Each transaction is posted against a specific card. The transaction owns the FK. Account is reached via the multi-hop route through card_cross_references — no direct FK to accounts.</summary>
    public string CardNumber { get; set; } = string.Empty;

    public MerchantInfo Merchant { get; set; } = new();
}