-- Generated by G.Tx T3 from COBOL copybooks. PostgreSQL target.
-- The copybooks are the SEMANTIC source: names, types, scale, enums.
-- Byte offsets, record lengths and FILLER are properties of the storage
-- engine being retired and deliberately do not appear here.

CREATE SCHEMA IF NOT EXISTS onlinetransactionmanagement;
SET search_path TO onlinetransactionmanagement;

-- enum candidate for carddemo_commarea.user_type (from 88-levels): CDEMO-USRTYP-ADMIN=A, CDEMO-USRTYP-USER=U
-- enum candidate for carddemo_commarea.pgm_context (from 88-levels): CDEMO-PGM-ENTER=0, CDEMO-PGM-REENTER=1

-- from COCOM01Y
CREATE TABLE carddemo_commarea (
    from_tranid                  char(4)         ,
    from_program                 varchar(8)      ,
    to_tranid                    char(4)         ,
    to_program                   varchar(8)      ,
    user_id                      varchar(8)      ,
    user_type                    char(1)         ,
    pgm_context                  smallint        ,
    cust_id                      integer         ,
    cust_fname                   varchar(25)     ,
    cust_mname                   varchar(25)     ,
    cust_lname                   varchar(25)     ,
    acct_id                      bigint          ,
    acct_status                  char(1)         ,
    card_num                     bigint          ,
    last_map                     varchar(7)      ,
    last_mapset                  varchar(7)      
);

-- from COTTL01Y
CREATE TABLE ccda_screen_title (
    title01                      varchar(40)     ,
    title02                      varchar(40)     ,
    thank_you                    varchar(40)     
);

-- from CSDAT01Y
CREATE TABLE ws_date_time (
    curdate_year                 smallint        ,
    curdate_month                smallint        ,
    curdate_day                  smallint        ,
    curtime_hours                smallint        ,
    curtime_minute               smallint        ,
    curtime_second               smallint        ,
    curtime_milsec               smallint        ,
    curdate_mm                   smallint        ,
    curdate_dd                   smallint        ,
    curdate_yy                   smallint        ,
    curtime_hh                   smallint        ,
    curtime_mm                   smallint        ,
    curtime_ss                   smallint        ,
    timestamp_dt_yyyy            smallint        ,
    timestamp_dt_mm              smallint        ,
    timestamp_dt_dd              smallint        ,
    timestamp_tm_hh              smallint        ,
    timestamp_tm_mm              smallint        ,
    timestamp_tm_ss              smallint        ,
    timestamp_tm_ms6             integer         
);

-- from CSMSG01Y
CREATE TABLE ccda_common_messages (
    msg_thank_you                varchar(50)     ,
    msg_invalid_key              varchar(50)     
);

-- from CVACT01Y
CREATE TABLE account (
    id                           bigint           NOT NULL,
    active_status                char(1)         ,
    curr_bal                     numeric(12,2)   ,
    credit_limit                 numeric(12,2)   ,
    cash_credit_limit            numeric(12,2)   ,
    open_date                    varchar(10)     ,
    expiraion_date               varchar(10)     ,
    reissue_date                 varchar(10)     ,
    curr_cyc_credit              numeric(12,2)   ,
    curr_cyc_debit               numeric(12,2)   ,
    addr_zip                     varchar(10)     ,
    group_id                     varchar(10)     ,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

-- from CVACT03Y
CREATE TABLE card_xref (
    card_num                     varchar(16)     ,
    cust_id                      integer         ,
    acct_id                      bigint          
);

-- from CVTRA05Y
CREATE TABLE tran (
    id                           varchar(16)      NOT NULL,
    type_cd                      char(2)         ,
    cat_cd                       smallint        ,
    source                       varchar(10)     ,
    desc                         varchar(100)    ,
    amt                          numeric(11,2)   ,
    merchant_id                  integer         ,
    merchant_name                varchar(50)     ,
    merchant_city                varchar(50)     ,
    merchant_zip                 varchar(10)     ,
    card_num                     varchar(16)     ,
    orig_ts                      varchar(26)     ,
    proc_ts                      varchar(26)     ,
    CONSTRAINT pk_tran PRIMARY KEY (id)
);

-- FOREIGN KEY CANDIDATES (column shared across tables).
-- Not asserted automatically: which side owns the relationship is a
-- domain decision for the human-approved design step.
--   acct_id                  appears in: card_xref, carddemo_commarea
--   card_num                 appears in: card_xref, carddemo_commarea, tran
--   cust_id                  appears in: card_xref, carddemo_commarea